containers:
  - name: main
    securityContext: unprivileged
    image: docker.hubteam.com/wailmer/blazar-executor-frontend-ubuntu:855
steps:
  - description: testing qa commit status
    container: main
    commands:
      - echo test

