containers:
  - name: main
    securityContext: unprivileged
    image: docker.hubteam.com/wailmer/blazar-executor-frontend-ubuntu:855

steps:
  - description: Testing webhook once more on 123456 hello
    container: main
    commands:
      - echo test
