containers:
  - name: main
    securityContext: unprivileged
    image: docker.hubteam.com/wailmer/blazar-executor-frontend-ubuntu:855

steps:
  - description: Webhook response better logging
    container: main
    commands:
      - echo test
